#! /bin/sh

# ------------------
# Autostart Programs
# ------------------

pgrep -x sxhkd > /dev/null || sxhkd &
killall flameshot &
killall picom &
$HOME/.config/polybar/launch.sh &
# redshift -x -P -O 9500k
redshift -x -P -O 3000k &
feh --bg-scale /home/emuel/images/wallpapers/MountainDark.jpg &
megasync &

# ------------------
# Variables
# ------------------

alias bc='bspc config'
alias br='bspc rule'
alias bn='bspc node'

# ------------------
# bspwm config
# ------------------

bc border_width         4
bc window_gap           8
bc split_ratio          0.50
bc borderless_monocle   true
bc gapless_monocle      false
bc single_monocle       true
bc focus_follows_pointer true
bspc monitor -d 1 2 3 4 5

bspc config focused_border_color  "#303030"
bspc config active_border_color   "#303030"
bspc config normal_border_color   "#1f1f1f"
bspc config presel_feedback_color "#1f1f1f"

# ------------------
# rules
# ------------------

br -a "MEGAsync" state=floating border=off
br -a Thunar:thunar state=floating
br -a Galculator state=floating center=true
br -a "peek" state=floating center=true
